ethereum-authentication-server:
  build: ./staging/ethereum-authentication-server
  ports:
   - 3000:3000
  command: "/bin/bash start.sh http://go-ethereum:8545 user-db FIREBASE-API-KEY"
  links:
   - go-ethereum
   - user-db
ethereum-web:
  build: ./staging/ethereum-sample-web
  ports:
   - 3001:3001
  command: "/bin/bash start.sh https://localhost:3000/"
  links:
   - ethereum-authentication-server
go-ethereum:
  build: ./staging/go-ethereum
  command: "/bin/bash /start.sh"
  ports:
   - 8545:8545
   - 30303:30303
user-db:
  build: ./staging/ethereum-user-db-docker
  ports:
   - 3306:3306
