ethereum-authentication-server:
  build: ./staging/ethereum-authentication-server
  ports:
   - 3000:3000
  command: "/bin/bash start.sh ETHEREUM-SERVER-URL user-db FIREBASE-API-KEY CONTRACT-ADDRESS MANDRILL-KEY MANDRILL-EMAIL-TO"
  links:
   - user-db
ethereum-web:
  build: ./staging/ethereum-sample-web
  ports:
   - 3001:3001
  command: "/bin/bash start.sh AUTH-SERVER-URL"
  links:
   - ethereum-authentication-server
user-db:
  build: ./staging/ethereum-user-db-docker
  ports:
   - 3306:3306
